Repository SashaLevkovich/middle.SandwormRampage.praktikum.yandex, pull requests merged in 2024-07, with the labels that each got.

#74 [SAN-41] Fix memory leaks
  memoryLeaks.md
  packages/client/src/features/GameEngine/GameEngine.test.tsx
  packages/client/src/features/GameEngine/GameEngine.tsx
  packages/client/src/features/GameEngine/index.ts
  packages/client/src/pages/forum/Forum.tsx
  packages/client/src/pages/game/Game.tsx
  packages/client/src/pages/landing/Landing.tsx
  packages/client/src/shared/helpers/drawGame.ts
  packages/client/src/shared/helpers/generateFoodPosition.ts
  packages/client/src/shared/helpers/getAngle.ts
  packages/client/src/shared/helpers/resetGames.ts
  packages/client/src/shared/helpers/updateGame.ts
  packages/client/src/shared/hooks/useGameEngine.test.tsx
  packages/client/src/shared/hooks/useGameEngine.ts
  packages/client/src/shared/hooks/useKeyboardControls.ts
Labels: enhancement, Инфра, Improvement

#75 [SAN-38] OAuth
  packages/client/src/app/api/index.ts
  packages/client/src/app/api/requests/oAuth.ts
  packages/client/src/pages/gameStart/GameStart.tsx
  packages/client/src/pages/signIn/SignIn.tsx
  packages/client/src/shared/constants/httpStatuses.ts
  packages/client/src/shared/helpers/getOAuthCodeFromUrl.ts
Labels: Ааторизация и регистрация

#76 Fix redux
  packages/client/src/app/appRoutes.tsx
  packages/client/src/app/redux/api/index.ts
  packages/client/src/app/redux/hooks.ts
  packages/client/src/app/redux/slice/user/index.ts
  packages/client/src/app/redux/store.ts
  packages/client/src/app/redux/thunk/user/getUser.ts
  packages/client/src/app/redux/thunk/user/logoutUser.ts
  packages/client/src/app/redux/thunk/user/signInUser.ts
  packages/client/src/components/Navbar/Navbar.tsx
  packages/client/src/components/PrivateRoute/PrivateRoute.tsx
  packages/client/src/entry-server.tsx
  packages/client/src/main.tsx
  packages/client/src/pages/gameStart/GameStart.tsx
  packages/client/src/pages/signIn/SignIn.tsx
  packages/client/src/shared/helpers/game/drawGame.ts
  packages/client/src/shared/helpers/game/generateFoodPosition.ts
  packages/client/src/shared/helpers/game/getAngle.ts
  packages/client/src/shared/helpers/game/resetGames.ts
  packages/client/src/shared/helpers/game/updateGame.ts
  packages/client/src/shared/helpers/registerServiceWorker.ts
  packages/client/src/shared/helpers/userLocalStorage.ts
  packages/client/src/shared/hooks/useGameEngine.ts
  packages/client/src/shared/redux/index.ts
  packages/client/src/shared/utils/userLocalStorage.ts
Labels: bug

#80 [SAN-44] Dark theme
  packages/client/src/app/redux/slice/user/index.ts
  packages/client/src/components/ButtonCustom/ButtonCustom.module.scss
  packages/client/src/components/ForumButton/ForumButton.module.scss
  packages/client/src/components/GameInfo/GameInfo.module.scss
  packages/client/src/components/GameOver/GameOver.module.scss
  packages/client/src/components/LeaderCard/LeaderCard.module.scss
  packages/client/src/components/Message/Message.module.scss
  packages/client/src/components/Navbar/Navbar.module.scss
  packages/client/src/components/Navbar/Navbar.tsx
  packages/client/src/features/ForumChat/ForumChat.module.scss
  packages/client/src/features/GameEngine/GameEngine.module.scss
  packages/client/src/index.scss
  packages/client/src/pages/errors/Errors.module.scss
  packages/client/src/pages/forum/Forum.module.scss
  packages/client/src/pages/game/Game.module.scss
  packages/client/src/pages/gameStart/GameStart.module.scss
  packages/client/src/pages/landing/Landing.module.scss
  packages/client/src/pages/leaderboard/Leaderboard.module.scss
  packages/client/src/pages/signUp/SignUp.module.scss
  packages/client/src/shared/constants/theme.ts
  packages/client/src/shared/styles/colors.css
  packages/client/src/shared/styles/colors.scss
  packages/client/src/shared/styles/shadowsAndGradients.scss
Labels: Feature

#82 [SAN-46] Add reactions on client
  packages/client/public/assets/add-reaction.svg
  packages/client/src/app/api/requests/reactions.ts
  packages/client/src/app/redux/rootReducer.ts
  packages/client/src/components/Message/Message.tsx
  packages/client/src/components/Reaction/Reaction.module.scss
  packages/client/src/components/Reaction/Reaction.tsx
  packages/client/src/components/Reaction/index.ts
  packages/client/src/features/EmojiPicker/EmojiPicker.module.scss
  packages/client/src/features/EmojiPicker/EmojiPicker.tsx
  packages/client/src/features/EmojiPicker/emojis-mock.json
  packages/client/src/features/EmojiPicker/index.ts
  packages/client/src/shared/helpers/reactionConvert.ts
Labels: Форум, Feature
